version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"

  broker:
    build: ./broker
    container_name: broker
    depends_on:
      - activemq
      - auldfellas
      - girlpower
      - dodgydrivers

  auldfellas:
    build: ./auldfellas
    container_name: auldfellas
    depends_on:
      - activemq

  dodgydrivers:
    build: ./dodgydrivers
    container_name: dodgydrivers
    depends_on:
      - activemq

  girlpower:
    build: ./girlpower
    container_name: girlpower
    depends_on:
      - activemq

